name: Backend CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - 'backend/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'backend/**'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Lint
        working-directory: ./backend
        run: npm run lint

      - name: TypeScript type check (no emit)
        working-directory: ./backend
        run: npx tsc --noEmit

      - name: Run tests
        working-directory: ./backend
        run: npm test

      - name: Decode SSH private key
        run: |
          echo "${{ secrets.SSH_KEY_B64 }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ~/.ssh/id_rsa

      - name: Deploy to production server
        shell: bash
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} << EOF
            cd /var/www/FinalProject-backend/backend
            git pull origin $BRANCH_NAME
            npm install
            pm2 describe CakeBackend > /dev/null && pm2 restart CakeBackend || pm2 start dist/server.js --name CakeBackend
          EOF
